# print("Vetit the dancer of Despacito")
# not , and , or are 3 logical operators
"""first_number = int(input("Insert your first number: "))
second_number = int(input("Insert your second number: "))
a = first_number * second_number
print("The sum of your 2 numbers are", a)
temp_celsius = float(input("Enter the temperature (in celsius): "))
temp_fahrenheit = (temp_celsius * 9/5) + 32
temp_rohmer = (temp_celsius * 4/5)
temp_kelvin = temp_celsius + 273
print("Your temperature converted to fahrenheit is ", temp_fahrenheit, "F")
print("Your temperature converted to rohmer is ", temp_rohmer, "R")
print("Your temperature converted to kelvin is ", temp_kelvin, "K")"""
#importing library
import turtle
"""turtle.color("red")
turtle.speed(2)
turtle.forward(200)
turtle.color("black")
turtle.left(120)
turtle.forward(200)
turtle.color("green")
turtle.right(240)
turtle.forward(200)
turtle.color("red")
turtle.speed(2)
turtle.forward(200)
turtle.color("black")
turtle.left(120)
turtle.forward(200)
turtle.color("green")
turtle.right(240)
turtle.forward(200)
turtle.color("red")
turtle.speed(2)
turtle.forward(200)
turtle.color("black")
turtle.left(120)
turtle.forward(200)
turtle.color("green")
turtle.right(240)
turtle.forward(200)
turtle.mainloop()"""
turtle.speed(5)
turtle.color("black", "peru")
turtle.begin_fill()
turtle.circle(30)
turtle.penup()
turtle.forward(30)
turtle.right(90)
turtle.pendown()
turtle.right(180)
turtle.forward(140)
turtle.penup()
turtle.right(90)
turtle.forward(60)
turtle.left(90)
turtle.pendown()
turtle.circle(30, 180)
turtle.penup()
turtle.left(90)
turtle.forward(60)
turtle.pendown()
turtle.right(90)
turtle.forward(140)
turtle.penup()
turtle.left(90)
turtle.forward(30)
turtle.pendown()
turtle.circle(30)
turtle.end_fill()
turtle.mainloop()

